# Matrix
- A matrix is a rectangular array of numbers 
- The size of a matrix is defined by the number of rows and columns it contains.


# Adition of Matrices
1. define two matrices with same data type elements in them.
2. define a third matrixC with 0 elements in it and of same sizede
3. fine the length of the matrix
4. add matrixA and matrixB matrices use the nested for loop
5. print MatrixC

In [1]:
MatrixA = [[2,7,3],
           [4 ,5,6],
           [7 ,8,9]]

MatrixB = [[7,2,6],
           [5,4,3],
           [2,1,0]]

MatrixC = [[0,0,0],
           [0,0,0],
           [0,0,0]]

MatLen = len(MatrixA)

for row in range(len(MatrixA)):
   for col in range(len(MatrixA[0])):
       MatrixC[row][col] = MatrixA[row][col] + MatrixB[row][col]

for Mat in MatrixC:
   print(Mat)


[9, 9, 9]
[9, 9, 9]
[9, 9, 9]


# Multiplcation of Matrices
1. define two matrices in whitch column of Matrix D equals the row of Matrix E.
2. define a Matrix F with 0 elements where Matrix F size is = D rows and E columns
3. fine the length of the Matrix D and E
4. Multiply matrixA and matrixB matrices use the nested for loop
5. print MatrixF

In [2]:
MatrixD = [[1,2,3],
           [4 ,5,6],
           [7 ,8,9]]

MatrixE = [[5,6,7,8],
           [1,2,3,4],
           [9,1,2,3]]

MatrixF = [[0,0,0,0],
           [0,0,0,0],
           [0,0,0,0]]

for Arow in range(len(MatrixD)):
   for Acol in range(len(MatrixD[0])):
       for Brow in range(len(MatrixE)):
           MatrixF[Arow][Acol] += MatrixD[Arow][Brow] * MatrixE[Brow][Acol]

for m in MatrixF:
   print(m)

[34, 13, 19, 0]
[79, 40, 55, 0]
[124, 67, 91, 0]


# Uing the numpy Lib
1. Addition
2. Subtration
3. Multiplication

In [3]:
from numpy import array, add, subtract, dot

MatrixG = array([[1, 3, 4],
                 [8, 5, 6]])
MatrixH = array([[8, 6, 9],
                 [9, 7, 6]])
MatrixD = [[1,2,3],
           [4 ,5,6],
           [7 ,8,9]]

MatrixE = [[5,6,7,8],
           [1,2,3,4],
           [9,1,2,3]]
# Add two matrices
print("Add Matrix H to Matrix G:")
MatrixI = add(MatrixG, MatrixH)
print(MatrixI)

# Subtract two matrices
print("Subtract Matrix G from Matrix H:")
MatrixJ = subtract(MatrixH, MatrixG)
print(MatrixJ)

Add Matrix H to Matrix G:
[[ 9  9 13]
 [17 12 12]]
Subtract Matrix G from Matrix H:
[[7 3 5]
 [1 2 0]]


## Calculate dot product from two Matrices

\begin{equation}
A\cdot B = \sum^n a_ib_i = u_1v_1 + u_2v_2 + ... + u_nv_n
\end{equation}

In [4]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

B = [[5, 6, 7, 8],
     [1, 2, 3, 4],
     [9, 0, 1, 2]]

print("dot product from two Matrices")
print(dot(A, B))

dot product from two Matrices
[[ 34  10  16  22]
 [ 79  34  49  64]
 [124  58  82 106]]


Calculate dot product from two 2-D arrays

In [5]:
A = array([[1, 2], [3, 4]])
B = array([[5, 6], [7, 8]])
print("dot product from two Arrays")
print(dot(A, B))

dot product from two Arrays
[[19 22]
 [43 50]]
